### ISSUE TITLE
Heat map toggle is not sticky

### ISSUE THREAD

**Issue by mgunther68** [lignumaqua/dump1090#2]
On page reload, if heat map was toggled ON, the heat map does not show and needs to be selected again. Maybe there is a reason for it? Or just an oversight?

**Comment by lignumaqua** [comment]
Yes, this was deliberate. The heat map is very resource intensive so it seemed sensible to have it always default to being off.

**Comment by mgunther68** [comment]
OK, that's fine, thanks for the explanation!
